### ISSUE TITLE
Possible Bug in "Work()"

### ISSUE THREAD

**Issue by Mazecreator** [awjuliani/dfp#5]
First off, great work!  Awesome concept and great visual of that concept it has really helped me.

I am not sure if it is my system setup with Python2, but I was getting "okay" results when running the training.  It would run up to about 18 deliveries and then fall back a bit like it overfit.  This didn't seem right to me so I started looking for an error (I had to update the ExperienceBuffer as it wouldn't work out of the box on my setup).

What I found was in the Work() of the DFP file this assignment:
                    s = s1
                    m = m1
                    g = g1

This appears to point s1 and s to the same memory location and the same for m & g.  This was causing some problem with the self.g assignment as well (usually as it restarted a new run or when battery ran low).

I have updated that section of code to look like this:
                    s = np.copy(s1)
                    m = []
                    m = m1[:]
                    g = g1[:]

For some reason, "m" was an array and m1 was a list so I changed m to a list for my usage.  Now my deliveries are pegged out around 28 and almost always runs the full 100 steps.  (I just noticed I changed my offsets = [1,2,3,4,5,6,7,8,12,16,24,32]  as I was debugging and didn't change back so your mileage may vary).

Thanks again for a great example of this powerfull RL approach.

**Comment by awjuliani** [comment]
Hi @Mazecreator, thanks for pointing this out. Please feel free to submit a pull request with your changes, and I will be happy to incorporate them.

**Comment by Mazecreator** [comment]
Here is a run with the update to the code to make sure it copies the values.  With the default setting:
offsets = [1,2,4,8,16,32] # Set of temporal offsets

![screenshot 2017-08-23 16 13 46](https://user-images.githubusercontent.com/18412448/29636326-30d90962-881e-11e7-80e1-222b135a5395.png)

**Comment by awjuliani** [comment]
Looks good. Thanks!
